star_logs/urls.py
'''定义URL模式'''
from django.urls import path,include
from . import views

app_name='star_logs'
urlpatterns=[
    #主页
    path('',views.index,name='index'),
    # display all the topics
    path('topics/',views.topics,name='topics'),
    path('topics/<int:topic_id>/',views.topic,name='topic'),
    #用于添加新主题
    path('new_topic/',views.new_topic,name='new_topic'),
]

starlog/starlog/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('star_logs.urls')),
]

starlog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('star_logs.urls')),
]

star_logs/models.py
from django.db import models

class Topic(models.Model):
    '''
    笔记主题
    '''
    text=models.CharField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        '''返回字符串'''
        return self.text
        
class Entry(models.Model):
    '''帖子或通知主题'''
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural='entries'
    def __str__(self):
        return f'{self.text[:50]}'

star_logs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['text']
        labels={'text':''}

star_logs/views.py
from django.shortcuts import render
from django.shortcuts import render
from .models import Topic
from .forms import TopicForm

def index(request):
    '''笔记的主页'''
    return render(request,'star_logs/index.html')

def topics(request):
    '''display all the topics in the page'''
    topics=Topic.objects.order_by('date_added')
    context={'topics':topics}
    return render(request,'star_logs/topics.html',context)
def topic(request,topic_id):
    '''显示单个主题及所有的条目'''
    topic=Topic.objects.get(id=topic_id)
    entries=topic.entry_set.order_by('date_added')
    context={'topic':topic,'entries':entries}
    return render(request,'star_logs/topic.html',context)

def new_topic(request):
    '''添加新主题'''
    if request.method !='POST':
        #未提交表单：创建
        form=TopicForm()
    else:
        #POST提交的数据：处理
        form=TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return render(request,'star_logs:topics')

    #显示空表单或指出数据无效
    context={'form':form}
    return render(request,'star_logs/new_topic.html',context)

star_logs/templates/star_logs/base.html
<p>
    <a href="{% url 'star_logs:index' %}">星笔记</a> -
    <a href="{% url 'star_logs:topics' %}">话题</a>
</p>


    
{% block content %}{% endblock content %}
<p>
    POWERED BY <a href="https://djangoproject.com">django</a>
</p>

star_logs/templates/star_logs/index.html

{% extends "star_logs/base.html" %}

{% block content %}
<h1>星笔记</h1>
<p>
    星辰（14）班在线笔记<br>
    让我们共同进步
</p>
{% endblock content %}

star_logs/templates/star_logs/new_topic.html
{% extends "star_logs/base.html" %}

{% block content %}
  <p>添加新主题：</p>

  <form action="{% url 'star_logs:new_topic' %}"method="post">
      {% csrf_token %} <!--防止跨站请求伪造-->
      {{form.as_p}}
      <button name="submit">添加新主题</button>
  </form>
{% endblock content %}

star_logs/templates/star_logs/topic.html
{% extends 'star_logs/base.html' %}

{% block content %}
    <p>主题：{{ topic }}</p>

    <p>全部：</p>
    <ul>
    {% for entry in entries %}
        <li>
        <p>
        {{ entry.date_added|date:'Y M d,H:i'}}
        </p>
        <p>
        {{entry.text|linebreaks}}
        </p>
    {% empty %}
        没有内容被添加。
        </li>
    {% endfor %}
    </ul>

{% endblock content %}

star_logs/templates/star_logs/topics.html
{% extends "star_logs/base.html" %}

{% block content %}
  
  <h1>话题</h1>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'star_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %} 
      <p>没有主题被添加。</p>
    {% endfor %}
  </ul>

  <a href="{% url 'star_logs:new_topic' %}">添加新主题</a>
  {% endblock content %} 